def line():
    ca = float(input("Ingrese el coeficiente A: "))
    cb = float(input("Ingrese el coeficiente B: "))
    cx1 = float(input("Ingrese el coeficiente X1: "))
    cx2 = float(input("Ingrese el coeficiente X2: "))
    print(f"El coeficiente A de su ecuación de la recta es: {ca}")
    print(f"El coeficiente B de su ecuación de la recta es: {cb}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {cx1}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {cx2}")
    print("")
    print("Para la siguiente ecuación:")
    ec = (f"\tY = {ca}X + {cb}")
    print(ec)
    y1 = ca * cx1 + cb
    y2 = ca * cx2 + cb
    print("")    
    print("Dados los siguientes puntos:")
    print("\tP1", (cx1, y1))
    print("\tP2", (cx2, y2))
    print("")
    distancia = ((cx2 - cx1)**2 + (y2 - y1)**2)**(0.5)
    print("La distancia entre ellos es:", distancia)
#line()